Added Fork Feature
CodeTrophs/Frontend pull request #301
Opened 2021-03-16 09:32 UTC by PushkarDureja

### Fixes #274 

- Project Repos can now be cloned using Fork button

2021-03-16 09:41 UTC, Anurag5086 approved these changes
LGTM

2021-03-16 14:34 UTC, msk4862 requested changes
@PushkarDureja Its going to show fork button on user's own repos too which shouldn't be the case. 
For this cases, you can just show number of forks as it is.

2021-03-16 14:43 UTC, PushkarDureja commented
> @PushkarDureja Its going to show fork button on user's own repos too which shouldn't be the case.
> For this cases, you can just show number of forks as it is.

Will work on it

2021-03-16 18:10 UTC, PushkarDureja commented
> @PushkarDureja Its going to show fork button on user's own repos too which shouldn't be the case.
> For this cases, you can just show number of forks as it is.

@msk4862 Can you please review the changes ?

2021-03-17 08:58 UTC, msk4862 commented on src/components/FeedCard.jsx
> +                    disabled = {isForked || User.name.replace(/\s+/g, '') === repo.full_name.split('/')[0]}
User.name is going to give full name of the user and repo.full_name.split('/')[0] will give username, these are not same.

2021-03-17 09:02 UTC, msk4862 commented
@PushkarDureja please test your changes on your local environment first before pushing them.

2021-03-17 11:02 UTC, msk4862 commented
@PushkarDureja after merge of [this](https://github.com/CodeTrophs/Backend/pull/174), you can simply use `username` itself for comparision.

2021-03-17 13:52 UTC, PushkarDureja commented on src/components/FeedCard.jsx
> +                    disabled = {isForked || User.name.replace(/\s+/g, '') === repo.full_name.split('/')[0]}
If I understood the problem correctly which was, user should not be able to fork its own repo right? And a user's repo name will always be of format `username/repo_name`. And If I am not wrong, the username shown on the navbar must be the github's username  So I guess extracting the username from `repo.full_name` and using the username from  UserContext (after removing spaces) should do the job. Please Correct me if I am wrong :) @msk4862

2021-03-17 14:12 UTC, msk4862 commented on src/components/FeedCard.jsx
> +                    disabled = {isForked || User.name.replace(/\s+/g, '') === repo.full_name.split('/')[0]}
@PushkarDureja `username` shown on the navbar is not github's username its the name of user.
For ex. your github name is `Pushkar` and github's username is `PushkarDureja`. 
So, `UserContext` will give you `Pushkar` not `PushkarDureja`.
I hope its clear now.

2021-03-20 06:46 UTC, msk4862 commented
@PushkarDureja yo can update the changes now, See [this](https://github.com/CodeTrophs/Backend/pull/174) for reference.

2021-03-20 07:54 UTC, PushkarDureja commented
@msk4862  Since ,now I can access the username, So I need to add the `username` property to the `UserContext` then I can use the appropriate check for forking. Is that correct ?

2021-03-20 12:42 UTC, msk4862 approved these changes

2021-03-20 12:43 UTC, msk4862 commented
Looks good to me :+1:

2021-03-20 13:57 UTC, pinkman7009 commented
Yes this is good

2021-03-20 13:58 UTC, pinkman7009 approved these changes

2021-03-23 10:05 UTC, PushkarDureja commented
is it good enough to be merged @aryasoni98 ?

2021-03-23 11:00 UTC, merged