Responsive Navigation bar added
CodeTrophs/Frontend pull request #309
Opened 2021-04-05 14:30 UTC by sheetalj2205

## Related Issue
Issue 303
- Info about the related issue
The header didn't have a navigation bar.
Closes: #[303]

### Describe the changes you've made
I have added the navigation bar in the header.
Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [ 
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

2021-04-05 14:43 UTC, pinkman7009 commented
Add the correct issue number and make a PR again. Also your code seems to have many file changes which aren't necessary.

2021-04-07 12:04 UTC, Anurag5086 requested changes
Make a separate css file for styles.

2021-04-07 12:04 UTC, Anurag5086 commented on src/components/Nav/Burger.jsx
> +  width: 2rem;
Please Make a separate css file for all the styles.

2021-04-07 12:04 UTC, Anurag5086 commented on src/components/Nav/Navbar.jsx
> +const Nav = styled.nav`
Make css file.

2021-04-07 12:04 UTC, Anurag5086 commented on src/components/Nav/RightNavbar.jsx
> +const Ul = styled.ul`
Make css file

2021-04-07 12:04 UTC, msk4862 commented
@sheetalj2205 Please create PR with your commits only and add screenshots as well.
> Before pushing your commit, pull the changes from `remote` and push it  in your local repo to synchronise your local repo with remote.

2021-04-12 16:12 UTC, pinkman7009 commented on src/components/Nav/RightNavbar.jsx
> +const Ul = styled.ul`
She has used styled components for this cause there is a functionality of the open prop. So I don't think an scss file can be created.

2021-04-14 13:12 UTC, closed without merging