testimonial ui improved
CodeTrophs/Frontend pull request #322
Opened 2021-04-11 05:53 UTC by shonali2600

## Related Issue
Improved Testimonial UI

Closes: #318 

### Describe the changes you've made
I've added the colour, shadow, border radius, to the card. And added border, shadow and improved hover effect on arrow buttons.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
![codetrophs](https://user-images.githubusercontent.com/57946528/114293955-4f4c6a00-9ab8-11eb-91d2-61c5162f1215.png)

2021-04-13 17:59 UTC, shonali2600 commented
@aryasoni98 kindly review my PR

2021-04-13 20:34 UTC, aryasoni98 commented
@shonali2600 Change the Red Colour to White background

2021-04-13 20:34 UTC, aryasoni98 reviewed
Change the Red To White Background

2021-04-14 05:33 UTC, msk4862 commented on src/scss/carousel.module.scss
> +  box-shadow: 10px 10px 7px 3px #2c030a;
change box shadow to `1px 1px 3px #5a5a5a` to maintain uniformity on the page.

2021-04-14 17:28 UTC, shonali2600 commented
![fcard](https://user-images.githubusercontent.com/57946528/114752966-8babee80-9d74-11eb-8893-21ecadc61a56.png)

Now please review, and let me know if any further changes to be made.

2021-04-14 18:39 UTC, msk4862 requested changes
@shonali2600 maybe you can convert images to rounded ones and add styled commas at the beginning of blockquote, something similar to [this](https://www.atompilot.com/wp-content/uploads/2017/08/peer-testimonial.jpg)

2021-04-16 05:24 UTC, shonali2600 commented
@msk4862 I made images rounded, but not able to add quote icon there, can you please help me

2021-04-16 06:02 UTC, shonali2600 commented
@msk added the quote icon and made the images round, now please review.

2021-04-16 06:03 UTC, shonali2600 commented
![quote](https://user-images.githubusercontent.com/57946528/114978845-7f747e00-9ea7-11eb-8b18-a7317a83ac81.png)

2021-04-16 08:19 UTC, msk4862 commented
@shonali2600 looks nice, but make sure all checks passes.

2021-04-16 08:48 UTC, pinkman7009 commented
make sure all the checks pass, and try to add some padding to the box because the picture looks too cramped up.

2021-04-16 08:55 UTC, pinkman7009 requested changes
try to add some padding to the box to create some space between the pictures and the border as it looks too cramped up now. and also make sure all the checks pass.

2021-04-16 09:45 UTC, shonali2600 commented
@pinkman7009 @msk4862 Added the padding, and all checks passed, now please review

2021-04-16 09:48 UTC, pinkman7009 approved these changes
looks good to me :D

2021-04-16 10:02 UTC, msk4862 approved these changes
Looks good :+1:

2021-04-17 11:15 UTC, Anurag5086 approved these changes
Looks good!

2021-04-17 18:28 UTC, aryasoni98 approved these changes
Nice 👍

2021-04-17 18:28 UTC, merged