Issue 329
CodeTrophs/Frontend pull request #339
Opened 2021-04-22 06:25 UTC by hsnice16

## Related Issue

Right now, on the hovering nav icon, the cursor is changing to pointer but on clicking it, nothing happens. So I think on clicking it route should change to '/' (or home page).

And in the footer, on hovering social handlers only the cursor is changing to a pointer type, if we also transform its size then it will look nicer.

Closes: #329

### Describe the changes you've made

Converted Nav-icon into a **Next** Link, and added code for hovering state of social-handles.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested on localhost.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

2021-04-22 06:29 UTC, hsnice16 commented
Please review and merge.

And don't know why showing 8 commits? I did only one.

2021-04-23 09:07 UTC, Anurag5086 commented on src/components/Nav/Navbar.jsx
> +            <img className= {styles['header-logo']} src="/logo/codetrophs.png" alt="" />
Add alt value

2021-04-23 09:08 UTC, Anurag5086 requested changes
Make sure the build check passes.

2021-04-23 11:24 UTC, hsnice16 commented on src/components/Nav/Navbar.jsx
> +            <img className= {styles['header-logo']} src="/logo/codetrophs.png" alt="" />
Thanks, I did this change.

2021-04-23 11:25 UTC, hsnice16 commented
Please, review once more.

2021-04-23 18:12 UTC, merged

2021-04-23 18:15 UTC, hsnice16 commented
Thanks

2021-04-26 20:11 UTC, hsnice16 commented
Will PR's, without labels count for GSSOC?