Made responsive for ipad and ipad pro
CodeTrophs/Frontend pull request #347
Opened 2021-04-28 11:00 UTC by sheetalj2205

## Related Issue

- Info about the related issue

Closes: #328 

### Describe the changes you've made
made responsive
Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

2021-04-28 15:56 UTC, msk4862 commented
@sheetalj2205 Please add screenshots too.

2021-04-28 18:28 UTC, Anurag5086 requested changes

2021-04-28 18:28 UTC, Anurag5086 commented on src/components/Carousel.jsx
> +  // function goToPrevious() {
remove comments

2021-04-30 15:04 UTC, sheetalj2205 commented on src/components/Carousel.jsx
> +  // function goToPrevious() {
I haven't made any changes in carousel.jsx.

2021-05-01 06:05 UTC, msk4862 reviewed
@sheetalj2205 add one screenshot for non-apple device too.

2021-05-01 16:20 UTC, sheetalj2205 commented
> @sheetalj2205 add one screenshot for non-apple device too.

done

2021-05-01 17:27 UTC, Anurag5086 commented on src/components/Carousel.jsx
> +  // function goToPrevious() {
Okay! Looks like others commits have also come. Fine no problem.

2021-05-01 17:29 UTC, Anurag5086 approved these changes

2021-05-01 17:30 UTC, Anurag5086 commented
looks good! 👍

2021-05-01 17:40 UTC, aryasoni98 approved these changes

2021-05-01 17:40 UTC, merged

2021-05-04 14:19 UTC, sheetalj2205 commented
I am not getting scores for this PR. Even the changes that I have made is not visible.