Navbar Updated new PR
CodeTrophs/Frontend pull request #353
Opened 2021-05-02 14:32 UTC by srrathi

## Related Issue

- Info about the related issue
- New Navbar according to the required design is updated

Closes: #[331]

### Describe the changes you've made
I've made a new navbar using bootstrap and react-bootstrap according to the design we required.

Give a clear description what modifications you have made
removed the previous navbar and added the new navbar

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot |
 updated screenshot |

2021-05-03 16:05 UTC, msk4862 commented
@srrathi add screenshot for mobile screen too.

2021-05-03 16:06 UTC, msk4862 reviewed
@srrathi add screenshot for mobile screen too.

2021-05-03 16:43 UTC, srrathi commented
> @srrathi add screenshot for mobile screen too.

sure @msk4862 
![image](https://user-images.githubusercontent.com/57089237/116905082-29038f80-ac5c-11eb-8350-bcaf186e8974.png)
![image](https://user-images.githubusercontent.com/57089237/116905515-b5ae4d80-ac5c-11eb-8a6f-935d2e951a6d.png)
![image](https://user-images.githubusercontent.com/57089237/116905401-8dbeea00-ac5c-11eb-83d6-6c0862e5834c.png)

2021-05-04 06:12 UTC, msk4862 commented on src/components/Navbar/header.jsx
> +                  <hr
@srrathi Maybe we can create a separate component for `hr`.  As it is used in multiple places.

2021-05-04 06:32 UTC, msk4862 requested changes

2021-05-04 06:32 UTC, msk4862 commented on src/components/Navbar/header.jsx
> +                <Dropdown.Item href="#/action-1">
![Screenshot from 2021-05-04 11-55-43](https://user-images.githubusercontent.com/24875366/116967388-cea41680-accf-11eb-956f-f38c69089976.png)
Remove this blue background on click of Menu item.

![Screenshot from 2021-05-04 11-48-06](https://user-images.githubusercontent.com/24875366/116967574-3c504280-acd0-11eb-9abc-54304582d5e6.png)
Also remove its grey highlighting on hover.

2021-05-04 10:05 UTC, srrathi commented on src/components/Navbar/header.jsx
> +                <Dropdown.Item href="#/action-1">
Okay @msk4862 I'll do that by EOD.

2021-05-04 10:06 UTC, srrathi commented on src/components/Navbar/header.jsx
> +                  <hr
Yeah sure. I'll do that.

2021-05-05 17:56 UTC, srrathi commented on src/components/Navbar/header.jsx
> +                <Dropdown.Item href="#/action-1">
> ![Screenshot from 2021-05-04 11-55-43](https://user-images.githubusercontent.com/24875366/116967388-cea41680-accf-11eb-956f-f38c69089976.png)
> Remove this blue background on click of Menu item.
> 
> ![Screenshot from 2021-05-04 11-48-06](https://user-images.githubusercontent.com/24875366/116967574-3c504280-acd0-11eb-9abc-54304582d5e6.png)
> Also remove its grey highlighting on hover.

@msk4862 I've made all the changes you requested please check.

2021-05-05 19:26 UTC, msk4862 commented
@srrathi have you tested again? Because Dropdown item bg is still blue on click and grey on hover.
You can use `.dropdown-item:active` and `.dropdown-item:hover` respectively to override styles.

2021-05-05 21:06 UTC, srrathi commented
> @srrathi have you tested again? Because Dropdown item bg is still blue on click and grey on hover.
> You can use `.dropdown-item:active` and `.dropdown-item:hover` respectively to override s

> @srrathi have you tested again? Because Dropdown item bg is still blue on click and grey on hover.
> You can use `.dropdown-item:active` and `.dropdown-item:hover` respectively to override styles.

@msk4862  I'm sorry the changes which i made worked earlier but now I've actually solved it. you can check now.

2021-05-06 06:59 UTC, msk4862 commented
Looks good now :+1:

2021-05-06 11:12 UTC, aryasoni98 approved these changes

2021-05-06 11:13 UTC, merged